---
fixtures:
  repositories:
    augeasproviders :
      repo: "https://github.com/simp/augeasproviders"
      branch: "simp-master"
    augeasproviders_sysctl:
      repo: "https://github.com/simp/augeasproviders_sysctl"
      branch: "simp-master"
    augeasproviders_core :
      repo: "https://github.com/simp/augeasproviders_core"
      branch: "simp-master"
    simplib: "https://github.com/simp/pupmod-simp-simplib"
    iptables: "https://github.com/simp/pupmod-simp-iptables"
    nfs: "https://github.com/simp/pupmod-simp-nfs"
    stdlib:
      repo: "https://github.com/simp/puppetlabs-stdlib"
      branch: "simp-master"
    sysctl: "https://github.com/simp/pupmod-simp-sysctl"
    svckill : "https://github.com/simp/pupmod-simp-svckill"
    simpcat : "https://github.com/simp/pupmod-simp-simpcat"
    compliance: "https://github.com/simp/pupmod-simp-compliance_markup"
  symlinks:
    autofs: "#{source_dir}"