---
fixtures:
  repositories:
    auditd: "https://github.com/simp/pupmod-simp-auditd"
    augeasproviders :
      repo: "https://github.com/simp/augeasproviders"
      branch: "simp-master"
    augeasproviders_sysctl:
      repo: "https://github.com/simp/augeasproviders_sysctl"
      branch: "simp-master"
    augeasproviders_core :
      repo: "https://github.com/simp/augeasproviders_core"
      branch: "simp-master"
    augeasproviders_grub :
      repo: "https://github.com/simp/augeasproviders_grub"
      branch: "simp-master"
    concat:
      # master is at 4.0.1, but we are bound to < 4.0.0 in our metadata.json
      repo: https://github.com/simp/puppetlabs-concat
      ref: 3.0.0
    haveged: "https://github.com/simp/puppet-haveged"
    logrotate: "https://github.com/simp/pupmod-simp-logrotate"
    pki: "https://github.com/simp/pupmod-simp-pki"
    rsyslog: "https://github.com/simp/pupmod-simp-rsyslog"
    simplib: "https://github.com/simp/pupmod-simp-simplib"
    simp_options: "https://github.com/simp/pupmod-simp-simp_options"
    iptables: "https://github.com/simp/pupmod-simp-iptables"
    stdlib: "https://github.com/simp/puppetlabs-stdlib"
    svckill : "https://github.com/simp/pupmod-simp-svckill"
  symlinks:
    autofs: "#{source_dir}"
