---
fixtures:
  repositories:
    augeasproviders:
      branch: 5.X
      repo: https://github.com/simp/augeasproviders
    augeasproviders_sysctl:
      branch: 5.X
      repo: https://github.com/simp/augeasproviders_sysctl
    augeasproviders_core:
      branch: 5.X
      repo: https://github.com/simp/augeasproviders_core
    simplib:
      repo: https://github.com/simp/pupmod-simp-simplib
      branch: 5.X
    iptables:
      repo: https://github.com/simp/pupmod-simp-iptables
      branch: 5.X
    nfs:
      repo: https://github.com/simp/pupmod-simp-nfs
      branch: 5.X
    stdlib:
      branch: 5.X
      repo: https://github.com/simp/puppetlabs-stdlib
    sysctl:
      repo: https://github.com/simp/pupmod-simp-sysctl
      branch: 5.X
    svckill:
      repo: https://github.com/simp/pupmod-simp-svckill
      branch: 5.X
    simpcat:
      repo: https://github.com/simp/pupmod-simp-simpcat
      branch: 5.X
    compliance:
      repo: https://github.com/simp/pupmod-simp-compliance_markup
      branch: 5.X
  symlinks:
    autofs: "#{source_dir}"
