---
fixtures:
  repositories:
    auditd: "https://github.com/simp/pupmod-simp-auditd"
    augeasproviders_core: "https://github.com/simp/augeasproviders_core"
    augeasproviders_grub: "https://github.com/simp/augeasproviders_grub"
    augeasproviders_sysctl: "https://github.com/simp/augeasproviders_sysctl"
    concat:
      # master is beyond 4.1.1, but has breaking changes to
      # how fragments are ordered (MODULES-6625)
      repo: https://github.com/simp/puppetlabs-concat
      ref: 4.1.1
    haveged: "https://github.com/simp/pupmod-simp-haveged"
    logrotate: "https://github.com/simp/pupmod-simp-logrotate"
    pki: "https://github.com/simp/pupmod-simp-pki"
    rsyslog: "https://github.com/simp/pupmod-simp-rsyslog"
    simplib: "https://github.com/simp/pupmod-simp-simplib"
    simp_options: "https://github.com/simp/pupmod-simp-simp_options"
    iptables: "https://github.com/simp/pupmod-simp-iptables"
    stdlib: "https://github.com/simp/puppetlabs-stdlib"
    svckill : "https://github.com/simp/pupmod-simp-svckill"
  symlinks:
    autofs: "#{source_dir}"
