---
fixtures:
  repositories:
    concat: "https://github.com/simp/puppetlabs-concat"
    pki: "https://github.com/simp/pupmod-simp-pki"
    simplib: "https://github.com/simp/pupmod-simp-simplib"
    stdlib: "https://github.com/simp/puppetlabs-stdlib"
  symlinks:
    autofs: "#{source_dir}"
