<%
  if ENV['BEAKER_HYPERVISOR']
    hypervisor = ENV['BEAKER_HYPERVISOR']
  else
    hypervisor = 'vagrant'
  end
-%>
HOSTS:
  el7:
    roles:
      - nfs_client
    platform:   el-7-x86_64
    box:        centos/7
    hypervisor: <%= hypervisor %>

  el8:
    roles:
      - nfs_client
      - nfs_server
      - default
    platform: el-8-x86_64
    box: centos/stream8
    hypervisor: <%= hypervisor %>

CONFIG:
  log_level: verbose
  type: aio
<% if ENV['BEAKER_PUPPET_ENVIRONMENT'] -%>
  puppet_environment: <%= ENV['BEAKER_PUPPET_ENVIRONMENT'] %>
<% end -%>
